# Generated by Django 4.2.6 on 2023-10-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
